name: Run-Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
    Dry-Run-Test:
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout repository
          uses: actions/checkout@v1
        - uses: actions/cache@v2
          id: cache
          with:
            python-version: '3.10'
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirement.txt') }}
        - name: Install pip dependencies
          if: steps.cache.outputs.cache-hit != 'true'
          run: |
            pip install --upgrade pip
            pip install -r requirement.txt

        - name: run test
          run: python -m robot -d Results testcases/functional_tests
          
 
