name: Run-Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
    Dry-Run-Test:
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout repository
          uses: actions/checkout@v1
        - uses: actions/cache@v2
          id: cache
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirement.txt') }}
        - name: Install pip dependencies
          run: |
            pip install --upgrade pip
            pip install -r requirement.txt
            pip install django-robots
        - name: run test
          run: python -m robot -d Results testcases/functional_tests
    
    generate_report:      
        if: always()
        needs: Dry-Run-Test
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Download reports
          uses: actions/download-artifact@v1
          with:
            name: reports
        - name: Send report to commit
          uses: joonvena/robotframework-reporter-action@v2.1
          with:
            gh_access_token: ${{ secrets.GITHUB_TOKEN }}
