name: Run-Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout repository
          uses: actions/checkout@v1
        - uses: actions/cache@v2
          id: cache
          with:
            python-version: '3.10'
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirement.txt') }}
        - name: Install pip dependencies
          if: steps.cache.outputs.cache-hit != 'true'
          run: |
            pip install --upgrade pip
            pip install -r requirements.txt
        - name: comment PR
          if: github.event_name == 'pull_request'
          uses: machine-learning-apps/pr-comment@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            path: robocop-summary.log
