name: Run-Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
    Run-Test:
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout repository
          uses: actions/checkout@v1
        - uses: actions/cache@v2
          id: cache
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirement.txt') }}
        - name: Install pip dependencies
          run: |
            pip install --upgrade pip
            pip install -r requirement.txt
            pip install django-robots
        - name: Run Test
          run: python -m robot -d Results testcases/functional_tests --output reports/outputChrome.xml
        - name: Set Robot Return Code
          run: |
             echo "ROBOT_RC=$?" >> "$GITHUB_ENV"  
        - name: If Auto Test Pass Rate Not 100%, Job Will Fail
          if: env.ROBOT_RC != '0'
          run: |
            echo "Auto Test Pass Rate Not 100%, Please Check Test Result"
            exit 1
